on:
  push:
    branches:
      - main
jobs:
  Job:
    runs-on: windows-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action
        with:
          path: README.md,index.md
          outputpath: out
